### PR TITLE
add first feature test (adding a contact)

### PR DESCRIPTION
**Pull request by sly7-7**
complete test with phone number

run rake minitest:features to execute, or rake minitest:all to execute with all other tests.

NOTE: For now the test pass only with selenium driver

### CODE REVIEW

**Comment by dgeb** [comment]
Thanks so much @sly7-7 !

I've merged this, and then moved the tests from /test/features -> /test/integration to conform with the latest Rails standards. Also, this allows the integration tests to be included automatically when running `rake test` without further configuration.

I was able to get the tests running with poltergeist on my end, so I made that the default driver instead of selenium (although both work for me). Perhaps you just need to update your phantomjs install?

This is a great start. Hopefully we can fill in the blanks soon. Thanks again!

**Comment by sly7-7** [comment]
Great :), I'll try to update phantomjs to make it work for me.
I think I will have the time to add others tests this week.

BTW, I've put this in test/features because it seems to be the default for minitest-rails/minitest-rails-capybara. Now I wonder if these gems are really useful. Anyway, this is not a major concern, I think we could improve the flow later if needed.

EDIT: Thanks @dgeb for pointing phantomjs update :), indeed, this make it work !

**Comment by dgeb** [comment]
@sly7-7 glad you got poltergeist / phantomjs working :+1: 

I've just pushed a new version of the contact creation test that uses `describe/setup/it` blocks like the other tests. We may still want to refactor a bit, but I find this more consistent than the `feature/scenario` blocks.

Any tests you have time to fill in would be great. Thanks again :)

**Comment by sly7-7** [comment]
Erf, there seem to have several dsls available... I find it better now :+1: I realize I don"t know if this style is coming from rspec, capybara, or minitest... I find myself a bit lost...

**Pull request merged**
