### PR TITLE
update ember-rails so we can remove useless barber dependency

### PR DESCRIPTION
**Pull request by sly7-7**

### CODE REVIEW

**Comment by dgeb** [comment]
After merging this and testing locally, I'm seeing ember-data still at REV 11, which means that the newer version (REV 12) from `/vendor` is not being used.

@sly7-7 is this working for you after rebasing against master?

**Comment by sly7-7** [comment]
Oh, I was mistakenly thinking that it would use ember-data master... Anyway, from the ember-rails README, for overriding default versions, they should be in /vendor/assets/ember/development and /vendor/assets/ember/production. I will change that and see if it works.

**Comment by dgeb** [comment]
@sly7-7 I think those override paths are relatively new in ember-rails. That should probably do it, but let me know otherwise. Thanks for following up :)

**Comment by sly7-7** [comment]
@dgeb It should be ok now. I've also removed other custom dependencies, such as jquery 1.8, handlebars, and ember. Using the default ones brought by the gemfile seems ok (as part of ember-data).
I hope this is all good now

**Comment by dgeb** [comment]
@sly7-7 merged - thanks again! :shipit:

**Comment by sly7-7** [comment]
You're welcome :)

**Pull request merged**
