### PR TITLE
Updating contact email address

### PR DESCRIPTION
**Pull request by kunalkamble**
Previously using `Handlebars.registerHelper` but it gets called only once so it was not updating contact email i'd, so changed it to `Ember.Handlebars.registerBoundHelper`.
`registerBoundHelper` calls function each time when we update view.
and 
Email mailto links issue, removed space between mailto: and email i'd.

### CODE REVIEW

**Comment by dgeb** [comment]
Thanks much @kunalkamble!

**Comment by sly7-7** [comment]
I think now, this is even simpler, if I undeerstood well, there is only one method for registering helper: http://emberjs.com/guides/templates/writing-helpers/. Am I wrong ?

**Comment by dgeb** [comment]
@sly7-7 Good catch - you're right. `Ember.Handlebars.helper` internally calls `Ember.Handlebars.registerBoundHelper` when necessary, but it's probably best to exclusively use  `Ember.Handlebars.helper` within our apps. [Updated](https://github.com/dgeb/ember_data_example/commit/7b32737e70af3cb3a2c716e0acf82465c368e8fe).

**Comment by sly7-7** [comment]
great :)

**Comment by kunalkamble** [comment]
cool!

**Pull request merged**
